### ISSUE TITLE
ws.wavesplatform.com is inaccessible!

### ISSUE THREAD

**Issue by yasharrashedi** [wavesplatform/waves-community#47]
ws.wavesplatform.com is down and inaccessible.

**Comment by twiggysmile** [comment]
Hello!

ws.wavesplatform.com a third-party service. So, it was disabled some time ago.

For development questions or processes related to Full Node operations, please join the specialized development sections on the Waves forum - https://forum.wavesplatform.com/c/developers and Discord chat - https://discordapp.com/invite/cnFmDyA

Thank you for your understanding!
